Qshop/Buyer/urls.py
from django.urls import path,re_path
from .views import *
from .views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('index/', index),
    re_path('^$', index),
    re_path('^$', cache_page(200)(index)),
    path('login/', login),
    path('register/', register),
    path('logout/', logout),
    path('goodslist/', goodslist),
    path('cart/', cart),
    path('person_info/', person_info),
    path('place_order/', place_order),
    path('place_order_more/', place_order_more),
    path('user_center_order/', user_center_order),
    path('user_center_site/', user_center_site),
    re_path('detail/(?P<goods_id>\d+)/', details),
    path('payorder/', payorderAli),
    path('payresult/', payresult),
    path('add_cart/', add_cart),
    path('delete_cart/', delete_cart),
    path('change_cart/', change_cart),
    path('get_goods/', get_goods),
    path('update_goods/', update_goods),
    path('myadd/', myadd),
    path('updateAddress/', updateAddress),
    path('get_code/', get_code),
]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from Buyer.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('buyer/', include('Buyer.urls')),
    path('seller/', include('Seller.urls')),
    re_path('^$', index),
    path('index/', index),

]

Qshop/Buyer/models.py
from django.db import models
from Seller.models import LoginUser, Goods

# Create your models here.
ORDER_STATUS = (
    (1, '未支付'),
    (2, '已支付'),
    (3, '待发货'),
    (4, '已发货'),
    (5, '完成'),
    (6, '拒收'),
)

class PayOrder(models.Model):
    order_number = models.CharField(max_length=32, verbose_name='订单编号')
    order_date = models.DateField(auto_now=True, verbose_name="创建日期")
    order_status = models.IntegerField(choices=ORDER_STATUS, verbose_name="订单状态")
    order_total = models.FloatField(verbose_name="订单总价")
    order_user = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE)
    order_address = models.IntegerField(verbose_name="订单收货地址", default=0)

    class Meta:
        db_table = 'payorder'
        verbose_name = '订单表'

class OrderInfo(models.Model):
    order_id = models.ForeignKey(to=PayOrder, on_delete=models.CASCADE)
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE)
    goods_price = models.FloatField(verbose_name='商品单价')
    goods_count = models.IntegerField(verbose_name="订单商品数量")
    goods_total_price = models.FloatField(verbose_name="商品小计")
    store = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE)
    order_status = models.IntegerField(choices=ORDER_STATUS, verbose_name="订单详情状态", default="1")

    class Meta:
        db_table = 'orderinfo'
        verbose_name = "订单详情表"

class Cart(models.Model):
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE, verbose_name='商品外键')
    goods_number = models.IntegerField(verbose_name='商品数量')
    cart_user = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name='买家')
    goods_total = models.FloatField(verbose_name='单件商品总价')
    payorder = models.CharField(default="0", verbose_name='订单表的订单号', max_length=32)

    class Meta:
        db_table = 'cart'
        verbose_name = '购物车表'


class validcode(models.Model):
    code = models.CharField(max_length=32, verbose_name='验证码内容')
    user = models.CharField(max_length=32, verbose_name='用户')
    data = models.DateTimeField(auto_now=True, verbose_name='创建时间')

Qshop/Buyer/views.py
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from Seller.models import *
from Buyer.models import *
# Create your views here.
import hashlib
from django.views.decorators.cache import cache_page
import logging
collect = logging.getLogger("django")


# 密码加密
def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()
    return result


# 主页装饰器
def LoginValid(func):
    def inner(request, *args, **kwargs):
        username = request.COOKIES.get('username')

        user_id = request.COOKIES.get("user_id")
        username_session = request.session.get('username')
        cookie_username = request.COOKIES.get('username')
        if username and username_session and username == username_session:
            flag = LoginUser.objects.filter(username=cookie_username, id=user_id, user_type=1).exists()
            if flag:
                return func(request, *args, **kwargs)
            else:
                return HttpResponseRedirect('/buyer/login/')
        else:
            return HttpResponseRedirect('/buyer/login')
    return inner


# 主页
@cache_page(120)
def index(request):
    print(request.COOKIES.get('username'))
    goods_type = GoodsType.objects.all()
    types = []
    for one in goods_type:
        goods = one.goods_set.order_by("-goods_price")
        if len(goods) > 4:
            goods_all = goods[:4]
            types.append({"type": one, "goods": goods_all})
        elif len(goods)>0 and len(goods)<=4:
            goods_all = goods
            types.append({"type": one, "goods": goods_all})
    return render(request, 'buyer/index.html', locals())


# 注册
def register(request):
    """
    完成注册功能
    :param request: 请求方式post
    :return:
    """
    email = request.POST.get('email')
    username = request.POST.get('user_name')
    password = request.POST.get('pwd')
    repassword = request.POST.get('cpwd')
    # 判空
    if email and password and repassword:
        if password == repassword:
            flag = LoginUser.objects.filter(email=email).exists()
            if flag:
                result = '邮箱已被注册！'
            else:
                LoginUser.objects.create(email=email, username=username, password=setPassword(password),user_type=1)
                result = '注册成功！'
        else:
            result = '两次输入的密码不一致！'
    else:
        result = '不能为空！'
    return render(request, 'buyer/register.html', locals())


# 登录
def login(request):
    if request.method == "POST":
        password = request.POST.get('pwd')
        username = request.POST.get('username')
        if password and username:
            user = LoginUser.objects.filter(username=username, password=setPassword(password), user_type=1).first()
            if user:
                # 登录成功跳转index，添加cookie和session
                response = HttpResponseRedirect('/buyer/index/')
                response.set_cookie("username", user.username)
                response.set_cookie("user_id", user.id)
                request.session["username"] = username
                collect.debug("%s is login" % user.username)
                return response
            else:
                result = '账户或者密码不正确'
                return render(request, 'buyer/login.html', locals())

        else:
            result = '账户或密码不能为空！'
            return render(request, 'buyer/login.html', locals())

    return render(request, 'buyer/login.html', locals())


@LoginValid
# 退出
def logout(request):
    response = HttpResponseRedirect('/buyer/login/')
    response.delete_cookie('username')
    response.delete_cookie('user_id')
    del request.session
    return response


#商品列表
def goodslist(request):
    req_type = request.GET.get("req_type")
    keywords = request.GET.get("keywords")
    if req_type == "findall":
        goods_type = GoodsType.objects.get(id=int(keywords))
        goods_all = goods_type.goods_set.all()
        print(goods_all)
    else:
        goods_all = Goods.objects.filter(goods_name__icontains=keywords).all()
        print(goods_all)
    goods_new = goods_all.order_by("-goods_pro_time")[:2]
    return render(request, 'buyer/goods_list.html', locals())


#商品详情
def details(request, goods_id):
    goods = Goods.objects.get(id=int(goods_id))
    address = UserAddress.objects.filter(status=1).first()
    print(address)
    return render(request, 'buyer/detail.html', locals())

@LoginValid
def cart(request):
    user_id = request.COOKIES.get("user_id")
    #按时间逆查找内容

    order_number = PayOrder.objects.filter(order_user=LoginUser.objects.get(id=user_id), order_status=1).values("order_number")
    cart = Cart.objects.filter(Q(payorder__in=order_number) | Q(payorder='0')).all().order_by("-id")
    return render(request, 'buyer/cart.html', locals())


@LoginValid
def person_info(request):
    return render(request, 'buyer/person_info.html', locals())


import time
@LoginValid
def place_order(request):
    ## 生成订单
    ## 获取 商品id
    ## 获取 商品购买数量
    ## 保存订单
    print(request.GET)
    user_id = request.COOKIES.get("user_id")
    goods_id = request.GET.get("goods_id")
    goods_count = request.GET.get("goods_count")
    address_id = request.GET.get("address_id")
    print(address_id)
    goods = Goods.objects.get(id=int(goods_id))
    ## 保存数据
    ## 保存订单
    payorder = PayOrder()
    payorder.order_number = str(time.time()).replace(".", "")
    payorder.order_status = 1  ## 未支付
    payorder.order_total = goods.goods_price * int(goods_count)
    payorder.order_user = LoginUser.objects.get(id=int(user_id))
    payorder.order_address_id = address_id
    payorder.save()
    ## 保存订单详情

    orderinfo = OrderInfo()
    orderinfo.order_id = payorder
    orderinfo.goods = goods
    orderinfo.goods_price = goods.goods_price
    orderinfo.goods_count = int(goods_count)
    orderinfo.goods_total_price = goods.goods_price * int(goods_count)
    orderinfo.store_id = goods.goods_store_id
    orderinfo.save()

    address = UserAddress.objects.get(id=address_id)
    print(address)
    return render(request, "buyer/place_order.html", locals())


@LoginValid
def user_center_order(request):
    ##返回登录用户订单
    user_id = request.COOKIES.get("user_id")
    payorder = PayOrder.objects.filter(order_user=LoginUser.objects.get(id=user_id)).all().order_by("order_status")
    return render(request, 'buyer/user_center_order.html', locals())


@LoginValid
def user_center_site(request):
    user_id = request.COOKIES.get("user_id")
    user = LoginUser.objects.get(id=user_id)
    if request.method == "POST":
        data = request.POST
        useraddress = UserAddress()
        useraddress.user = user
        useraddress.address = data.get("address")
        useraddress.phone = data.get("phone")
        useraddress.name = data.get("name")
        useraddress.status = 0
        useraddress.save()

    user_address_all = UserAddress.objects.filter(user=user).all()

    return render(request, 'buyer/user_center_site.html', locals())


def updateAddress(request):
    if request.method == "POST":
        print(request.POST)
        address_id = request.POST.get("address")
        print(address_id)
        ## 完成修改地址状态
        ## 2. 修改之前选中的地址状态
        user_address = UserAddress.objects.filter(status=1).first()
        user_address.status = 0
        user_address.save()

        ## 1. 修改选中的地址的状态
        user_address = UserAddress.objects.filter(id=address_id).first()
        user_address.status = 1
        user_address.save()

        return HttpResponseRedirect("/buyer/user_center_site/")


from Qshop.settings import alipay


#订单支付
def payorderAli(request):
    order_id = request.GET.get("order_id")
    payorder = PayOrder.objects.get(id=order_id)
    order_string = alipay.api_alipay_trade_page_pay(
        subject='生鲜交易',
        out_trade_no=payorder.order_number,
        total_amount=str(payorder.order_total),
        return_url="http://127.0.0.1:8000/buyer/payresult/",
        notify_url=None
    )
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    return HttpResponseRedirect(result)

#支付结果
def payresult(request):
    out_trade_no = request.GET.get("out_trade_no")
    payorder = PayOrder.objects.get(order_number=out_trade_no)
    payorder.order_status = 2
    payorder.save()

    payorder.orderinfo_set.all().update(order_status=2)
    return render(request, 'buyer/payresult.html', locals())


#添加购物车
@LoginValid
def add_cart(request):
    goods_id = request.POST.get("goods_id")
    count = request.POST.get("count", 1)
    user_id = request.COOKIES.get("user_id")
    goods = Goods.objects.get(id=goods_id)
    user = LoginUser.objects.get(id=user_id)
    #保存
    has_cart = Cart.objects.filter(goods=goods, cart_user=user, payorder = '0').first()
    if has_cart:  ##已经有
        has_cart.goods_number += int(count)
        has_cart.goods_total += int(count) * goods.goods_price
        has_cart.save()
    else:
    ## 没有 ## 保存
        cart = Cart()
        cart.goods = goods
        cart.goods_number = int(count)
        cart.cart_user = LoginUser.objects.get(id=user_id)
        cart.goods_total = int(count) * goods.goods_price
        cart.save()
    return JsonResponse({"code": 10000, "msg": "添加购物车成功"})


def place_order_more(request):
    #生成订单
    #获取 购物车id
    user_id = request.COOKIES.get("user_id")
    data = request.POST
    data = data.items()
    res = []
    for key, value in data:
        if key.startswith("cartid"):
            res.append(value)
    user = LoginUser.objects.get(id=user_id)

    #生成订单  2件  1笔订单  2笔订单详情
    if len(res) != 0:
        payorder = PayOrder()
        payorder.order_number = str(time.time()).replace(".", "")
        payorder.order_status = 1
        payorder.order_total = 0
        payorder.order_user = user
        payorder.save()

        order_total = 0
        order_count = 0
        #订单详情
        for c_id in res:    #c_id  购物车id
            cart = Cart.objects.get(id=c_id)

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
{% block style %}

{% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
                    {% if request.COOKIES.username %}
                        <a href="#">{{request.COOKIES.username}}</a>
                        <span>|</span>
                        <a href="/buyer/logout/">退出</a>
                    {% else %}
                        <a href="/buyer/login/">登录</a>
                        <span>|</span>
                        <a href="/buyer/register/">注册</a>
                    {% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/buyer/person_info/">用户中心</a>
					<span>|</span>
					<a href="/buyer/cart/">我的购物车</a>
					<span>|</span>
					<a href="/buyer/user_center_order">我的订单</a>
				</div>
			</div>
		</div>
	</div>
	<div class="search_bar clearfix">
		<a href="/buyer/index/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="keywords" id = "keywords" placeholder="搜索商品">
			<input type="button" onclick="getgoods()" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="/buyer/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
    {% block content %}
    {% endblock %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
	<script type="text/javascript">
		{#BCSlideshow('focuspic');#}
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');
	</script>
    <script>
        // 定义一个方法  方法名字为  getgoods   发送请求
        function getgoods() {
            //  获取填入的 搜索值
            var keywords = $("#keywords").val()
            //  发送请求，打开列表页
            url = "http://127.0.0.1:8000/buyer/goodslist/?req_type=search&keywords="+keywords;
            window.location.href = url;   //  js中跳转页面的方法

        }

    </script>
{% block script %}

{% endblock %}
</body>
</html>

Qshop/Buyer/templates/buyer/cart.html
{% extends "buyer/base.html" %}
{% block title %}
    购物车
{% endblock %}
{% block content %}
    	<div class="total_count">全部商品<em>{{ cart.all.count }}</em>件</div>
    <ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/buyer/place_order_more/" method="post" >
    {% csrf_token %}

    {% for one in cart %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="cartid_{{ one.id }}" class="goods_box" value="{{ one.id }}"></li>
		<li class="col02"><img src="/static/{{ one.goods.goods_picture }}"></li>
		<li class="col03">{{ one.goods.goods_name }}<br><em>{{ one.goods.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05" >{{ one.goods.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ one.goods_number }}" >
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07" >{{ one.goods_total }}元</li>
		<li class="col08"><a href="/buyer/delete_cart/?cart_id={{ one.id }}">删除</a></li>
	</ul>

    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" id="all_box"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total_mount">0</em><br>共计<b id="number">0</b>件商品</li>
		<li class="col04">
            <input type="submit" value="去结算">
        </li>
	</ul>
</form>
{% endblock %}


{% block script %}
    <script>

    $("#all_box").click(
        function () {
            //点击全选，将所有的全部选中
            //console.log(this.checked);
            if (this.checked){
                $(".goods_box").prop("checked", true);
            }else {
                $(".goods_box").prop("checked", false)
            }
            add()
        }
    )
    $(".goods_box").each(
        function () {
            $(this).click(
                function () {
                    console.log(1111)
                    console.log(this.checked)
                    if (!this.checked){
                        $("#all_box").prop("checked", false)
                    }
                    add()
                }
            )
        }
    );

    function add() {
        var dict = {"num":0, "total_mount":0};
        $(".goods_box").each(
            function () {
                if (this.checked){
                    var number = parseInt($(this).parents(".cart_list_td").find(".num_show").val());
                    var total = parseInt($(this).parents(".cart_list_td").find(".col07").text());
                    console.log(total);
                    dict.num+=1;
                    dict.total_mount +=total
                }
            }
        );
        $("#number").text(dict.num);
        $("#total_mount").text(dict.total_mount);
    }



    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/detail.html
{% extends 'buyer/base.html' %}

{% block title %}
    商品详情页
{% endblock %}

{% block content %}


	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img style="height: 100%;width: 100%;" src="/static/{{ goods.goods_picture }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_description }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="price">{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" id="num" value="1">
					<a id="add" href="javascript:;" class="add fr">+</a>
					<a id="minus" href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
            <div class="total">总价：<em><span id="total">{{ goods.goods_price }}</span> 元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" id="buynow">立即购买</a>
				<a href="javascript:;" class="add_cart" onclick="add_cartnew()" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/buyer/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/buyer/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>

{% endblock %}
{% block script %}
    <script>
    $("#add").click(
        function () {
            // 计算加法
            // 获取 当前的 数量值
            var number = parseInt($("#num").val());  //  转 int 类型
            //  数量值  加 1
            number = number + 1

            // 计算总价  单价 * 数量
            price = parseFloat($("#price").text());
            total_mount = (price * number).toFixed(2)
            //  将计算出的 数量和 总价 设置在相对应得标签内
            $("#num").val(number);
            $("#total").text(total_mount);
        }
    );
    $("#minus").click(
        function () {
            // 计算减法
            var number = parseInt($("#num").val());  //  转 int 类型
            number = number - 1;
            if (number <= 1){
                number = 1
            }
            price = parseFloat($("#price").text());
            total_mount = (price * number).toFixed(2);
            $("#num").val(number);
            $("#total").text(total_mount);
        }
    );

    $("#buynow").click(
        function () {
            var goods_count = $("#num").val();  //  购买数量
            var goods_id = {{ goods.id }};
            var address_id = {{ address.id }}
                console.log(address_id)
            url = "http://127.0.0.1:8000/buyer/place_order/?goods_count="+goods_count + "&goods_id=" +
                    goods_id + "&address_id=" + address_id;
            window.location.href = url;
        }
    )



    </script>

     <script>
        function add_cartnew() {
            console.log(11111);
            var goods_id = {{ goods.id }};
            count = $("#num").val()

            send_data = {
                "goods_id":goods_id,
                "count":count,
                "csrfmiddlewaretoken":"{{ csrf_token }}"
            };
            $.ajax({
                url:'/buyer/add_cart/',
                type:'post',
                data:send_data,
                success:function (data) {
                    console.log(data);
                    alert(data.msg)
                },
                error:function (error) {
                    console.log(error)
                }
            })
        }
    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/myadddemo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load myadd %}

{{ 20 | hh}}

{{ 10| mymanyadd:100 }}

{% myalladd 10 20 30 40 %}

</body>
</html>

Qshop/Buyer/templates/buyer/payresult.html
{% extends "buyer/base.html" %}
{% block title %}
    支付结果
{% endblock %}

{% block content %}
    <div class="list_model">
        <h1>支付结果</h1>
        <table>
            {% for key, value in request.GET.items %}
                <tr>
                    <td>{{ key }}:</td>
                    <td>{{ value }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

Qshop/Buyer/templates/buyer/user_center_order.html
{% extends "buyer/base.html" %}
{% block title %}
    用户订单
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="/buyer/person_info/">· 个人信息</a></li>
				<li><a href="/buyer/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/buyer/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for one in payorder %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ one.order_date }}</li>
					<li class="col02">订单号:{{ one.order_number }}</li>
					<li class="col02 stress">{{ one.get_order_status_display }}</li>
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order in one.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ order.goods.goods_picture }}"></li>
									<li class="col02">{{ order.goods.goods_name }}<em>{{ order.goods.goods_price }}/500g</em></li>
									<li class="col03">{{ order.goods_count }}</li>
									<li class="col04">{{ order.goods_total_price }}元</li>
								</ul>
                                    {% endfor %}
							</td>
							<td width="15%">{{ one.order_total }}元</td>
                        {% if one.order_status == 1 %}
                            <td width="15%">待付款</td>
							<td width="15%"><a href="/buyer/payorder/?order_id={{ one.id }}" class="oper_btn">去付款</a></td>
                        {% else %}
                            <td width="15%">已付款</td>
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                        {% endif %}
						</tr>
					</tbody>
				</table>
                {% endfor %}
				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}